---

- name: Ensure workdir exists
  file:
    path: "{{ cfssl_workdir_bin }}"
    state: directory
    mode: 0755

- name: "check if bin exists"
  stat:
    path: "{{ cfssl_workdir_bin }}/{{ item_i }}"
  register: "stat_out"

- name: Downloading cfssl binaries
  get_url:
    url: "https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/{{ item_i }}_{{ cfssl_version }}_{{ cfssl_os }}_{{ cfssl_arch }}"
    dest: "{{ cfssl_workdir_bin }}/{{ item_i }}"
    mode: 0755
    owner: "{{ cfssl_owner }}"
    group: "{{ cfssl_group }}"
    checksum: "sha256:{{ cfssl_checksum_url }}"
  when: not(stat_out.stat.exists)
  tags:
    - cfssl