---
# tasks file for cfssl

- include: install.yml
  when: cfssl_install

- include: gen-ca.yml
  when: "{{ cfssl_gen_ca }}"

- include: gen-cert.yml
  with_items: "{{ cfssl_certs }}"
  loop_control:
    loop_var: icert