---

# Dependencies:

- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - "{{ bootstrap_workdir }}"

- include: etcd.yml

- include: svc-setup-cp.yml
